import logging
from pathlib import Path
from common import PROJECT_DIR

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

logger.info("\nStarting plot retrieval...\n")

# 1. File đầu vào (Do UI tạo ra)
INPUT_PLOT_PATH = PROJECT_DIR / "input_plot.txt"

# 2. File đầu ra (Chuẩn hóa để subplot.py đọc)
OUTPUT_PLOT_PATH = PROJECT_DIR / "plot.txt"


def retrieve_plot() -> str:
    """
    Read the plot text from 'input_plot.txt' generated by the UI.
    """
    if not INPUT_PLOT_PATH.exists():
        raise FileNotFoundError(
            f"Input file not found: {INPUT_PLOT_PATH}\n"
            "Please enter the plot in the UI and click 'Save Plot' or 'Start'."
        )

    logger.info(f"Reading plot from: {INPUT_PLOT_PATH}")
    text = INPUT_PLOT_PATH.read_text(encoding="utf-8").strip()

    if not text:
        raise ValueError(f"The file {INPUT_PLOT_PATH} is empty. Please enter plot text in the UI.")

    return text


def main():
    # Đảm bảo thư mục tồn tại
    PROJECT_DIR.mkdir(parents=True, exist_ok=True)

    try:
        # Đọc plot từ file input của UI
        plot_text = retrieve_plot()

        # Lưu sang file chuẩn 'plot.txt' để các bước sau sử dụng
        OUTPUT_PLOT_PATH.write_text(plot_text, encoding="utf-8")
        logger.info(f"Successfully saved standardized plot to: {OUTPUT_PLOT_PATH}")
        
        logger.info("\nPlot retrieval completed successfully.\n")
        
    except Exception as e:
        logger.error(f"Failed to retrieve plot: {e}")
        raise e  # Dừng chương trình nếu lỗi

if __name__ == "__main__":
    main()